### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by thehitponcho** [tebl/C64-Kernal-Switcher#2]
Hello @tebl 

I'm a bit of a noob, so please forgive these questions if they seem simplistic.

- Are JP1 and JP2 used to manually switch between the different ROMs?
- What modifications can be made to these boards if we just want to use them as a 2332/2364 to 2732/2764 adapter?
- The original project from BWACK that this project was created from is now using an ATtiny85 chip instead of the PIC. Is it possible to do the same with your boards (with or without modifications)?

Regards

**Comment by tebl** [comment]
Yes, the switches allow you to manually set rhe activated kernal, that way
you could potentially have a replacement for basic, kernal and character
ROM in one as well (without installing the PIC).

Attiny chip does not have the same pinouts so I would expect rewireing to
make fit.

søn. 17. mai 2020, 23:37 skrev Poncho <notifications@github.com>:

**Comment by thehitponcho** [comment]
Thank you for your reply. I plan on ordering 5 boards from PCBWay soon. I will use 1 or 2 boards to make KERNEL ROMs each with multiple kernels. Then I would like to use the remaining boards for backup BASIC and CHARACTER ROMs. 

Does this board support all of the 27xx EPROMS (i.e.  2764, 27256 and 27512) ?

Do you have any documentation on how the switches must be configured to use the different sized EPROMS?

**Comment by tebl** [comment]
You'd have to check the datasheets for the specifics, but the board was
designed with the 27c256 in mind. 27c64 should work when leaving a13/a14
unjumpered. 27c512 should work if you flash the data two times
sequentially, but you would not get the intended capacity though I have not
tested it myself.

man. 18. mai 2020, 06:52 skrev Poncho <notifications@github.com>:

**Comment by thehitponcho** [comment]
Thank you for all your help. BTW - I have already ordered your Joystick Switcher. I am still waiting for the parts to arrive and am quite excited to build these. Thanks for all your hard work.
